### ISSUE TITLE
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                             

### ISSUE THREAD

**Issue by b0unc3** [VictorLin000/YOLOv3_mask_detect#1]
Hi,

I run git-lfs clone your repository, but this is the output:

> batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                             

Can you please help?
Thanks.

**Comment by VictorLin000** [comment]
Sorry for that, Just ignore LFS message, I had upload dataset and weights on GoogleDrive, you can follow Data section in README.
Please let me know if this work for you. Thanks

**Comment by b0unc3** [comment]
Hi,

works like a charm now!
Thank you very much!
