### ISSUE TITLE
Hello, I want to ask what the category "none" represents？

### ISSUE THREAD

**Issue by wangxiaoshuai223** [VictorLin000/YOLOv3_mask_detect#3]
Hello, I want to ask what the category "none" represents？

**Comment by VictorLin000** [comment]
"none" means that the mask is been wearing but not in the proper position. (for example: Mask_28.jpg)

Sorry for the poor naming.
You can get rid of "none" category cause there's not enough data for it, just classify to "bad" category.

**Comment by wangxiaoshuai223** [comment]
Thank you！ Jack Jack 邮箱：wangxiaoshuaixx428@gmail.com 签名由 网易邮箱大师 定制 On 08/28/2020 20:09, VictorLin wrote: "none" means that the mask is been wearing but not in the proper position. (for example: Mask_28.jpg) Sorry for the poor naming. You can get rid of "none" category cause there's not enough data for it, just classify to "bad" category. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
